### ISSUE TITLE
✨ [Feature] DB 관련 설정하기

### ISSUE THREAD

**Issue by Austin-Choi** [Chat-niverse/Chat-niverse_BE#1]
### Description

프로젝트를 위한 DB 설정을 진행합니다.
영속적인 데이터가 필요한지 논의하여 MySQL 사용 여부를 확인합니다.
기획상 필요하다면 MySQL yml과 환경변수를 설정합니다.
필요하지 않다면 MySQL dependency를 삭제합니다.
안쓰기로 함

Redis yml과 환경변수를 설정합니다.
RedisConfig와 RedisManager를 설정합니다.

### Todo

- [x] MySQL 안쓸 거니까 관련 설정 삭제 
- [x] Redis yml, env 설정
- [x] config 패키지 하위에 RedisConfig 추가
- [x] service 패키지 하위에 RedisManager 인터페이스와 구현체 추가
