### ISSUE TITLE
✨ [Feature] ChatGpt API 처리 Controller와 Service 작성

### ISSUE THREAD

**Issue by Austin-Choi** [Chat-niverse/Chat-niverse_BE#2]
### Description

ChatGpt API 요청과 응답을 수행할 Controller와 Service의 기본 뼈대를 잡고 주석을 추가합니다.

### Todo

- [x] jackson-databind, spring-boot-configuration-processor 의존성을 추가합니다.
- [x] api 키는 env에 등록하고 yml과 Value 어노테이션으로 관리합니다.
- [x] Controller와 관련 Service를 추가합니다.
