### ISSUE TITLE
✨ [Feature] 데이터 영속화를 위한 MongoDB 설정

### ISSUE THREAD

**Issue by Austin-Choi** [Chat-niverse/Chat-niverse_BE#8]
### Description

휘발성으로 관리되던 유저 데이터를 MongoDB를 이용해 저장합니다.
프로젝트에 MongoDB를 설정하고 유저의 닉네임, 세계관, 플레이어 성향, 목표, 모험 시작 일자, 모험 종료 일자 를 기록합니다. 

### Todo

- [ ] MongoDB 기본 설정
- [ ] nickname, worldview, charsetting, aim, advStartTime, advEndTime 저장
- [ ] nickname으로 나의 세계를 설정하면 읽어올 수 있게 수정
