### ISSUE TITLE
✨ [Feature] 간단한 로그인 기능 추가

### ISSUE THREAD

**Issue by Austin-Choi** [Chat-niverse/Chat-niverse_BE#9]
### Description

사용자 닉네임으로 로그인하는 간단한 로그인 기능을 추가합니다.
닉네임은 중복될 수 없으며 닉네임과 비밀번호를 입력하면 로그인되는 기능입니다.
사용자는 내 기록에서 MongoDB에서 조회한 내 탐험 기록을 볼 수 있게 하기 위함입니다.

### Todo

- [ ] Users 테이블 생성
- [ ] user_id, nickname, password, created_at, deleted_at 속성 추가
- [ ] 로그인하는 CRUD 구현
- [ ] 내 탐험기록 조회, 로그아웃, 로그인 구현
